PUT localhost:8085/api/users/registration/0ad35b81-ad81-4316-b41a-0280b4dd2ecd
Content-Type: application/json

{
  "name": "newUser",
  "email": "asdfasdf",
  "password": "asdfasdf"
}

### Get user by id
GET localhost:8085/api/users/0ad35b81-ad81-4316-b41a-0280b4dd2ecd

### login
POST localhost:8085/api/users/login
Content-Type: application/json

{
  "name": "newUser",
  "password": "asdfasdf"
}